# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tiramisuserver_pb2 as tiramisuserver__pb2


class TiramisuServerStub(object):
    """The string reversal service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLegality = channel.unary_unary(
                '/tiramisuserver.TiramisuServer/getLegality',
                request_serializer=tiramisuserver__pb2.TiramisuProgram.SerializeToString,
                response_deserializer=tiramisuserver__pb2.TiramisuResult.FromString,
                )


class TiramisuServerServicer(object):
    """The string reversal service definition.
    """

    def getLegality(self, request, context):
        """Function invoked to send the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TiramisuServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLegality': grpc.unary_unary_rpc_method_handler(
                    servicer.getLegality,
                    request_deserializer=tiramisuserver__pb2.TiramisuProgram.FromString,
                    response_serializer=tiramisuserver__pb2.TiramisuResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tiramisuserver.TiramisuServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TiramisuServer(object):
    """The string reversal service definition.
    """

    @staticmethod
    def getLegality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tiramisuserver.TiramisuServer/getLegality',
            tiramisuserver__pb2.TiramisuProgram.SerializeToString,
            tiramisuserver__pb2.TiramisuResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
