# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tiramisuserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tiramisuserver.proto\x12\x0etiramisuserver\"_\n\x0fTiramisuProgram\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08schedule\x18\x02 \x01(\t\x12,\n\toperation\x18\x03 \x01(\x0e\x32\x19.tiramisuserver.Operation\"Z\n\x0eTiramisuResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08legality\x18\x02 \x01(\x08\x12\x0f\n\x07isl_ast\x18\x03 \x01(\t\x12\x17\n\x0f\x65xecution_times\x18\x04 \x01(\t*(\n\tOperation\x12\x0c\n\x08LEGALITY\x10\x00\x12\r\n\tEXECUTION\x10\x01\x32\x62\n\x0eTiramisuServer\x12P\n\x0bgetLegality\x12\x1f.tiramisuserver.TiramisuProgram\x1a\x1e.tiramisuserver.TiramisuResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tiramisuserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_OPERATION']._serialized_start=229
  _globals['_OPERATION']._serialized_end=269
  _globals['_TIRAMISUPROGRAM']._serialized_start=40
  _globals['_TIRAMISUPROGRAM']._serialized_end=135
  _globals['_TIRAMISURESULT']._serialized_start=137
  _globals['_TIRAMISURESULT']._serialized_end=227
  _globals['_TIRAMISUSERVER']._serialized_start=271
  _globals['_TIRAMISUSERVER']._serialized_end=369
# @@protoc_insertion_point(module_scope)
